repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.0
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, snowflake]
        additional_dependencies: ['dbt-snowflake', 'sqlfluff-templater-dbt']
      - id: sqlfluff-fix
        args: [--dialect, snowflake]
        additional_dependencies: ['dbt-snowflake', 'sqlfluff-templater-dbt']